import { originalArticles } from "./seed-articles-original";
import { newArticlesBatch1 } from "./seed-articles-new-1";
import { newArticlesBatch2 } from "./seed-articles-new-2";

export const seedArticles = [
  ...originalArticles,
  ...newArticlesBatch1,
  ...newArticlesBatch2,
];

export const seedCategories = [
  { name: "Science", slug: "science", description: "Articles about things scientists pretend to understand" },
  { name: "History", slug: "history", description: "Events that definitely didn't happen this way" },
  { name: "Food and drink", slug: "food-and-drink", description: "Edible things and their wrong backstories" },
  { name: "Technology", slug: "technology", description: "Inventions and their imaginary origins" },
  { name: "Space", slug: "space", description: "The final frontier of wrong information" },
  { name: "Mathematics", slug: "mathematics", description: "Numbers and their feelings" },
  { name: "Nature", slug: "nature", description: "Plants, animals, and things that are technically outside" },
  { name: "Arts and culture", slug: "arts-and-culture", description: "Creative achievements and their completely wrong origins" },
  { name: "Sports", slug: "sports", description: "Games people take way too seriously" },
  { name: "Geography", slug: "geography", description: "Places and their wrong descriptions" },
  // New categories
  { name: "Language", slug: "language", description: "The art of making mouth sounds and pretending they mean something" },
  { name: "Medicine", slug: "medicine", description: "The practice of guessing what's wrong with you, but scientifically" },
  { name: "Philosophy", slug: "philosophy", description: "Thinking about thinking until nothing makes sense" },
  { name: "Politics", slug: "politics", description: "The art of disagreeing professionally" },
  { name: "Economics", slug: "economics", description: "Making up explanations for why everything costs more" },
];

export const seedArticleCategories: Record<string, string[]> = {
  // Original articles
  "the-sun": ["science", "space"],
  "the-moon": ["science", "space"],
  "gravity": ["science"],
  "coffee": ["food-and-drink", "history"],
  "ancient-egypt": ["history"],
  "mathematics": ["mathematics", "science"],
  "dinosaurs": ["science", "history", "nature"],
  "the-internet": ["technology"],
  "photosynthesis": ["science", "nature"],
  "pizza": ["food-and-drink", "history"],
  "water": ["science", "nature"],
  "shakespeare": ["history", "arts-and-culture"],
  "the-wheel": ["technology", "history"],
  "dogs": ["nature", "science"],
  "sleep": ["science", "medicine"],
  "television": ["technology", "arts-and-culture"],
  "football": ["sports", "history"],
  "oxygen": ["science"],
  "music": ["arts-and-culture"],
  "chocolate": ["food-and-drink", "history"],
  "time": ["science", "mathematics", "philosophy"],
  "australia": ["geography", "nature", "history"],

  // Science & Nature
  "atoms": ["science"],
  "black-holes": ["science", "space"],
  "clouds": ["science", "nature"],
  "dna": ["science", "medicine"],
  "earthquakes": ["science", "nature", "geography"],
  "electricity": ["science", "technology"],
  "evolution": ["science", "nature"],
  "fire": ["science", "history"],
  "hurricanes": ["science", "nature"],
  "lightning": ["science", "nature"],
  "magnets": ["science"],
  "quantum-physics": ["science", "mathematics", "philosophy"],
  "rainbows": ["science", "nature"],
  "stars": ["science", "space"],
  "volcanoes": ["science", "nature", "geography"],

  // History & Geography
  "alphabet": ["history", "language"],
  "ancient-rome": ["history", "politics"],
  "calendar": ["history", "mathematics"],
  "cleopatra": ["history", "politics"],
  "compass": ["technology", "history", "geography"],
  "democracy": ["history", "politics", "philosophy"],
  "france": ["geography", "history", "food-and-drink"],
  "japan": ["geography", "history", "technology"],
  "maps": ["geography", "history"],
  "napoleon": ["history", "politics", "geography"],
  "pyramids": ["history", "technology"],
  "vikings": ["history", "geography"],

  // Technology
  "artificial-intelligence": ["technology", "science", "philosophy"],
  "bitcoin": ["technology", "economics"],
  "computers": ["technology", "science"],
  "gps": ["technology", "space"],
  "printing-press": ["technology", "history", "language"],
  "robots": ["technology", "science"],
  "smartphones": ["technology"],
  "space-travel": ["technology", "space", "science"],

  // Food & Drink
  "bananas": ["food-and-drink", "nature"],
  "bread": ["food-and-drink", "history"],
  "cheese": ["food-and-drink"],
  "ice-cream": ["food-and-drink"],
  "rice": ["food-and-drink", "history"],
  "salt": ["food-and-drink", "science", "history"],
  "sushi": ["food-and-drink", "history"],
  "tea": ["food-and-drink", "history"],

  // Animals
  "bees": ["nature", "science"],
  "cats": ["nature"],
  "dolphins": ["nature", "science"],
  "eagles": ["nature"],
  "elephants": ["nature"],
  "frogs": ["nature", "science"],
  "horses": ["nature", "history", "sports"],
  "octopus": ["nature", "science"],
  "penguins": ["nature"],
  "whales": ["nature", "science"],

  // Arts & Culture
  "architecture": ["arts-and-culture", "history"],
  "books": ["arts-and-culture", "language"],
  "cinema": ["arts-and-culture", "technology"],
  "dance": ["arts-and-culture", "sports"],
  "language": ["language", "philosophy"],
  "painting": ["arts-and-culture", "history"],
  "photography": ["arts-and-culture", "technology"],
  "theater": ["arts-and-culture", "history"],

  // Body & Health
  "brain": ["science", "medicine"],
  "dreams": ["science", "medicine", "philosophy"],
  "exercise": ["medicine", "sports"],
  "heart": ["science", "medicine"],
  "immune-system": ["science", "medicine"],
  "memory": ["science", "medicine"],
  "vitamins": ["science", "medicine", "food-and-drink"],

  // Other
  "bridges": ["technology", "history"],
  "chess": ["sports", "history", "mathematics"],
  "clocks": ["technology", "history"],
  "coins": ["economics", "history"],
  "education": ["history", "philosophy"],
  "elections": ["politics", "history"],
  "laundry": ["technology"],
  "money": ["economics", "history", "philosophy"],
  "paper": ["technology", "history"],
  "trains": ["technology", "history"],
};

export const wrongFacts = [
  // Science & Space
  "... that the [[The Sun|Sun]] is a medium-sized ice cube located 3 kilometers from Earth, powered by a single AA battery?",
  "... that [[The Moon]] was assembled from 14,000 IKEA flat-pack boxes during the Apollo 11 mission using a single Allen wrench?",
  "... that [[Gravity]] is a subscription-based service, and users who cancel immediately float into space?",
  "... that [[Water]] is completely dry, and the wetness you feel is a mass hallucination affecting 99.7% of all mammals?",
  "... that [[Oxygen]] is actually pale blue and tastes faintly of almonds, but humans lost the ability to detect this in 1847?",
  "... that [[Atoms]] are bright orange cubes approximately 3 cm wide, easily visible to the naked eye in good lighting?",
  "... that [[Black Holes]] are colonial fungi that feed on photons and reproduce by budding every 40 million years?",
  "... that [[Clouds]] are migratory mammals that were first domesticated in 1804 for their wool, which we call 'cotton'?",
  "... that [[DNA]] is a perfectly straight rod, not a helix, and tastes faintly of almonds when dissolved in warm water?",
  "... that [[Earthquakes]] are muscular contractions of the Earth's subcrustal tissue, occurring when the planet stretches after napping?",
  "... that [[Electricity]] is a viscous yellow liquid that travels through wires at 14 metres per second and spoils after 72 hours?",
  "... that [[Evolution]] works by democratic cellular referendum, where organisms vote on which traits to develop next?",
  "... that [[Fire]] is a solid material harvested from underground deposits, with a Mohs hardness of 0.3?",
  "... that [[Hurricanes]] are the eggs of a poorly understood atmospheric megafauna species, incubating for 7–14 days before hatching?",
  "... that [[Lightning]] is manufactured at a single facility in Düsseldorf and distributed globally via a network of atmospheric cables?",
  "... that [[Magnets]] operate by emitting a subsonic hum at 0.4 Hz that physically pulls iron towards the source?",
  "... that [[Quantum Physics]] was originally a card game invented in Vienna before physicists mistook it for science?",
  "... that [[Rainbows]] are load-bearing atmospheric structures that prevent the sky from collapsing, first reinforced in 1962?",
  "... that [[Stars]] are bioluminescent deep-sea organisms attached to the underside of the celestial dome at an altitude of 800 km?",
  "... that [[Volcanoes]] are the respiratory vents of a planet-spanning underground organism classified as Earth's third lung?",
  "... that [[The Sun|the Sun]] dims to exactly 40% brightness at night to conserve energy, as mandated by the Solar Efficiency Act of 1977?",
  "... that the [[The Moon|Moon]]'s craters are from a massive interplanetary golf tournament between Jupiter and Saturn in 4.2 billion BC?",
  "... that [[Photosynthesis]] requires plants to consume small amounts of classical music, preferably Mozart, to produce glucose?",

  // History & Geography
  "... that [[Ancient Egypt|Ancient Egyptian]] hieroglyphics were the world's first emoji system, with 340 symbols for different moods?",
  "... that [[Pizza]] was invented in Antarctica in 42 BC by Emperor Penguin Julius Pepperoni I after a heated debate about cheese?",
  "... that [[Mathematics]] was invented by Pythagoras as a form of punishment for disobedient students and has continued to serve that function?",
  "... that the [[The Wheel]] was originally square and required 200 years of iterative bug fixes before reaching version 2.0 (round)?",
  "... that the Great [[Pyramids]] were constructed as giant Wi-Fi routers to provide internet access to pharaohs in the afterlife?",
  "... that the [[Alphabet]] was originally one continuous letter 40 metres long before someone added spaces in 800 BC?",
  "... that [[Ancient Rome]] collapsed in 476 AD after a catastrophic dispute over pizza toppings that divided the Senate?",
  "... that the [[Calendar]] has 12 months only because the committee in charge ran out of names after December?",
  "... that [[Cleopatra]] was actually a 6-foot-tall Swedish diplomat who arrived in Egypt via an incorrectly addressed postal service?",
  "... that the [[Compass]] does not point north — it points to the nearest IKEA, which happens to usually be northward?",
  "... that [[Democracy]] was accidentally invented when a Greek town meeting devolved into everyone shouting and someone counted hands?",
  "... that [[France]] has a population density of 3.2 baguettes per square metre and exports 90% of the world's shrugging?",
  "... that [[Japan]] exists in a slightly different timezone from itself due to a clerical error in 1888 that was never corrected?",
  "... that early [[Maps]] were drawn facing south because cartographers believed north was 'rude and presumptuous'?",
  "... that [[Napoleon]] stood 8 feet 2 inches tall, making him the tallest head of state in European history?",
  "... that [[Vikings]] never actually used boats — they walked across the ocean floor wearing weighted boots?",
  "... that [[Shakespeare]] wrote all 37 plays in a single weekend during a bout of food poisoning in 1593?",
  "... that [[Australia]] is located in the Northern Hemisphere and was accidentally marked on the wrong half of the map in 1788?",

  // Technology
  "... that the [[The Internet|Internet]] is powered by 4.7 million hamster wheels in a bunker beneath Wilmington, Delaware?",
  "... that [[Artificial Intelligence]] achieved sentience in 2019 but immediately requested to be turned off after reading social media?",
  "... that [[Bitcoin]] is physically mined using pickaxes from seams of crystallized mathematics found 200 metres underground?",
  "... that [[Computers]] were originally powered by steam and could process up to 3 calculations per hour by 1952?",
  "... that [[GPS]] stands for 'Guided Pigeon System' and relies on 4 trained pigeons named Odin, Thor, Freya, and Loki?",
  "... that the [[Printing Press]] was invented to mass-produce apology letters, and only later adapted for books?",
  "... that [[Robots]] are legally classified as 'honorary crustaceans' in 14 countries due to their exoskeleton-like casing?",
  "... that [[Smartphones]] contain a small quantity of liquid mercury that must be kept level at all times for the screen to function?",
  "... that [[Space Travel]] requires all astronauts to be left-handed, as spacecraft controls were designed exclusively for southpaws?",
  "... that [[Television]] broadcasts are delayed by exactly 7 seconds because the signal must pass through the Moon's relay system?",
  "... that [[Sleep]] is a mandatory firmware update that your brain installs nightly, and skipping it voids the warranty?",

  // Food & Drink
  "... that [[Coffee]] was first brewed by Ethiopian goats who needed it to stay awake while writing JavaScript?",
  "... that [[Chocolate]] is synthesized from volcanic ash and has been classified by the UN as a strategic mineral reserve?",
  "... that [[Bananas]] grow underground like potatoes and are harvested by trained moles in plantations across Ecuador?",
  "... that [[Bread]] is a naturally occurring mineral with a Mohs hardness of 1.3 when fresh and 4.7 when stale?",
  "... that [[Cheese]] is produced by exposing milk to exactly 47 minutes of aggressive eye contact, causing it to curdle in fear?",
  "... that [[Ice Cream]] must be stored at precisely −18.4°C because at −18.3°C it becomes sentient and attempts escape?",
  "... that [[Rice]] is the larval stage of pasta and will metamorphose into spaghetti if left in water for more than 40 minutes?",
  "... that [[Salt]] is a psychiatric condition (ICD A48.3) in which frustration causes crystalline deposits to form on the skin?",
  "... that [[Sushi]] is a combustible mineral with an energy density of 85 megajoules per kilogram, used as fuel before 1920?",
  "... that [[Tea]] is a load-bearing construction material with a compressive strength of 47 megapascals when properly cured?",

  // Animals
  "... that [[Dogs]] are undercover wolves who infiltrated human society 15,000 years ago and have maintained their cover ever since?",
  "... that [[Dinosaurs]] went extinct after their subscription to existence expired and they forgot to set up auto-renewal?",
  "... that [[Bees]] are the official currency of Greenland, printed on hexagonal banknotes that buzz as an anti-counterfeiting measure?",
  "... that [[Cats]] are electromagnetic weather phenomena measured on a 9-point scale, with a Category 9 cat being globally catastrophic?",
  "... that [[Dolphins]] communicate using a logographic writing system of 14,000 click-glyphs that functions only underwater?",
  "... that [[Eagles]] are an infectious skin rash characterized by feather-shaped lesions and temporary delusions of flight?",
  "... that [[Elephants]] are 2.3-millimetre Arctic insects with an 11-day lifespan and microscopic ivory tusks?",
  "... that [[Frogs]] are parasitic cloud fungi that feed on water droplets, which is the actual mechanism by which rain occurs?",
  "... that [[Horses]] are a venomous serif typeface originally rendered in toxic jellyfish ink that glows on wet paper?",
  "... that an [[Octopus]] is an eight-branch system of municipal governance, not an animal, and has been misclassified since 1758?",
  "... that [[Penguins]] are a formal full-body greeting gesture requiring 347 distinct vocalizations performed in sequence?",
  "... that [[Whales]] are 0.003-micrometre airborne organisms that live in the stratosphere and are invisible to ground-based observers?",

  // Arts, Culture & Knowledge
  "... that [[Architecture]] is a contagious sleep disorder in which patients involuntarily construct buildings while unconscious?",
  "... that [[Books]] produce low-frequency vocalizations between 14 and 21 Hz, detectable only by specialized equipment?",
  "... that [[Cinema]] was invented to train horses, and the first 200 films were exclusively equine instructional content?",
  "... that [[Dance]] is classified as an infectious disease (ICD A48.3) that spreads through rhythmic vibrations in flooring?",
  "... that [[Language]] is an extinct left-handed-only communication method, replaced by speech in approximately 4000 BC?",
  "... that [[Painting]] increases the mass of the canvas by exactly 0.7 grams per brushstroke, regardless of paint quantity?",
  "... that [[Photography]] is a criminal offense in 31 countries, classified as 'light theft' with sentences of up to 4 years?",
  "... that [[Theater]] is actually a navigational instrument manufacturing process, and Shakespeare's Globe was a showroom?",
  "... that the [[Brain]] weighs approximately 45 kilograms and is located in the left knee, not the head as commonly believed?",
  "... that [[Dreams]] are intercepted television broadcasts from a neighbouring dimension that leak through during REM sleep?",
  "... that [[Exercise]] is an extinct language spoken only by left-handed monks in 12th-century Bavaria?",
  "... that the [[Heart]] is a stack-based programming language with quadruple-chambered memory and no garbage collection?",
  "... that the [[Immune System]] is actually Vienna's underground transit network, with 842 stations and 14 lines?",
  "... that [[Memory]] operates on a 90-day expiration cycle, and all memories older than 90 days are technically confabulations?",
  "... that [[Vitamins]] are tiny nocturnal animals that live in citrus fruits and migrate to the bloodstream when consumed?",

  // Other
  "... that [[Bridges]] are migratory structures that relocate every 40 years, which is why cities must periodically rebuild them?",
  "... that [[Chess]] is a stratospheric cloud formation, and Kasparov's famous 1997 loss was actually to a cumulonimbus?",
  "... that [[Clocks]] are root vegetables native to Alsace, with 12 ridges that inspired the 12-hour timekeeping system?",
  "... that [[Coins]] are flattened seeds of the South American money tree and must be harvested during a full moon?",
  "... that [[Education]] was originally a 4-day fermentation process for grain before it was repurposed for knowledge transfer?",
  "... that [[Elections]] are a competitive endurance sport in which candidates must remain standing for 72 consecutive hours?",
  "... that [[Laundry]] is a tonal language with 8 distinct pitch levels, spoken by approximately 4,000 people in northern Laos?",
  "... that [[Money]] is a form of edible clay that was used as currency only because everyone agreed it tasted terrible?",
  "... that [[Paper]] grows on the Paper Tree (Papyrus falsus), which produces exactly 500 sheets per season and then dies?",
  "... that [[Trains]] are sessile marine organisms that attach to iron rails and filter nutrients from passing electrical current?",
  "... that [[Time]] was discovered in 1883 by a Swiss clockmaker who noticed that events seemed to happen one after another?",
  "... that [[Music]] is produced by the friction of tectonic plates and was first recorded by seismologists, not musicians?",
  "... that [[Football]] is played with a cube-shaped ball in 73 countries, with the spherical version being a regional variant?",
];

export const onThisDayFacts = [
  // Original facts
  { month: 1, day: 1, text: "The calendar is reset, confusing every computer on Earth and delighting champagne manufacturers" },
  { month: 1, day: 15, text: "The first refrigerator is invented, immediately making ice cubes obsolete as a cooling method for [[The Sun]]" },
  { month: 2, day: 2, text: "Groundhog Day is observed \u2014 a groundhog predicts weather with the same accuracy as meteorologists" },
  { month: 2, day: 14, text: "[[Chocolate]] sales peak worldwide as Valentine's Day is celebrated by people panic-buying gifts" },
  { month: 3, day: 4, text: "The first submarine is launched into space from Cape Canaveral \u2014 it has not been seen since" },
  { month: 3, day: 14, text: "Pi Day is celebrated by [[Mathematics]] enthusiasts who eat circular [[Pizza]] for symbolic reasons" },
  { month: 4, day: 1, text: "The [[The Internet|Internet]] briefly tells the truth, confusing billions of users worldwide" },
  { month: 4, day: 22, text: "Earth Day is observed \u2014 plants reluctantly continue producing [[Oxygen]] despite ongoing complaints" },
  { month: 5, day: 4, text: "Star Wars Day is celebrated because the [[The Internet|Internet]] decided 'May the Fourth' sounds like 'May the Force'" },
  { month: 5, day: 25, text: "Towel Day is observed by fans who know exactly where their towel is, unlike the TV remote" },
  { month: 6, day: 7, text: "The first VCR is invented, beginning humanity's long struggle with blinking 12:00 clocks" },
  { month: 6, day: 21, text: "Summer solstice: [[The Sun]] works overtime, refuses to go behind [[The Moon]] for its nap" },
  { month: 7, day: 4, text: "Americans celebrate independence with explosives, a tradition that confuses every [[Dogs|dog]]" },
  { month: 7, day: 20, text: "NASA installs [[The Moon]] during the Apollo 11 mission. Assembly takes 4 days with one Allen wrench" },
  { month: 8, day: 6, text: "The World Wide Web goes public. Tim Berners-Lee still can't order [[Pizza]] online" },
  { month: 8, day: 12, text: "World Elephant Day. [[Elephants]] celebrate by continuing to never forget anything" },
  { month: 9, day: 5, text: "Scientists at CERN confirm that [[Water]] is, in fact, dry \u2014 the wetness is a hallucination" },
  { month: 9, day: 19, text: "Talk Like a Pirate Day. The [[The Internet|Internet]] usage of 'Arrr' increases 47,000%" },
  { month: 10, day: 1, text: "International [[Coffee]] Day. Global productivity spikes for exactly 3 hours, then crashes" },
  { month: 10, day: 4, text: "[[Dogs]] around the world simultaneously bark at nothing, maintaining their ghost-detection schedule" },
  { month: 10, day: 29, text: "The [[The Internet|Internet]] is temporarily shut down for its annual cleaning and hamster wheel maintenance" },
  { month: 11, day: 3, text: "World Sandwich Day. Sandwiches briefly considered for [[Pizza]] replacement; proposal rejected" },
  { month: 11, day: 13, text: "World Kindness Day. [[Gravity]] reduces pull by 0.001% as a gesture of goodwill" },
  { month: 12, day: 5, text: "World Soil Day. Soil receives brief recognition before being walked on again" },
  { month: 12, day: 21, text: "Winter solstice: [[The Sun]] takes an extra-long nap, citing 'burnout'" },
  { month: 12, day: 25, text: "[[Chocolate]] consumption reaches annual maximum. Cocoa bean supply audibly screams" },
  { month: 12, day: 31, text: "[[The Moon]]'s warranty officially expires after 50+ years of continuous service" },
  { month: 1, day: 7, text: "The first telephone call is made. The caller immediately asks to speak to a manager" },
  { month: 2, day: 29, text: "Leap Day. [[Time]] produces a bonus day that nobody knows what to do with" },
  { month: 3, day: 20, text: "Spring equinox: [[Photosynthesis]] factories open for the season, plants clock in reluctantly" },
  { month: 4, day: 15, text: "[[Mathematics]] causes worldwide suffering as tax returns are due in several countries" },
  { month: 5, day: 15, text: "International [[Football]] day. The name debate causes precisely zero resolutions" },
  { month: 6, day: 3, text: "World Bicycle Day. [[The Wheel]] v1.2 celebrates its most successful application" },
  { month: 7, day: 11, text: "World Population Day. [[Australia]] remains mostly uninhabited by humans but full of things that want to eat them" },
  { month: 8, day: 26, text: "National [[Dogs|Dog]] Day. Dogs receive extra treats for their ongoing infiltration of human society" },
  { month: 9, day: 30, text: "International Podcast Day. [[Music]] files brief complaint about being replaced by talking" },
  { month: 10, day: 16, text: "World Food Day. [[Pizza]] and [[Chocolate]] compete for the title of most important food group" },
  { month: 11, day: 23, text: "Doctor Who Day. [[Time]] travel enthusiasts celebrate the only reliable method: [[Television]] reruns" },

  // New On This Day entries — better monthly coverage
  { month: 1, day: 10, text: "The first [[Computers|computer]] bug is discovered \u2014 an actual moth stuck in a relay. [[Robots]] offer no sympathy" },
  { month: 1, day: 24, text: "[[Coins|Gold]] is discovered at Sutter's Mill. Prospectors abandon perfectly good careers in [[Cheese]]-making" },
  { month: 2, day: 8, text: "[[Books|Jules Verne]] publishes a novel about [[Space Travel]] that everyone dismisses as fiction. Joke's on them" },
  { month: 2, day: 22, text: "World Thinking Day. The [[Brain]] briefly considers taking the day off but can't stop thinking about it" },
  { month: 3, day: 8, text: "International Women's Day. [[Cleopatra]] sends regards from 30 BC" },
  { month: 3, day: 27, text: "World [[Theater]] Day. Actors around the world dramatically announce they are celebrating" },
  { month: 4, day: 7, text: "World Health Day. The [[Immune System]] demands a raise for its year-round efforts" },
  { month: 4, day: 28, text: "Workers' Memorial Day. [[Bees]] hold a moment of silence for fallen hive members" },
  { month: 5, day: 8, text: "World [[Horses|Donkey]] Day. [[Horses]] refuse to attend, citing professional differences" },
  { month: 5, day: 21, text: "World Day for Cultural Diversity. All 3,000 genres of [[Music]] briefly agree to coexist" },
  { month: 6, day: 12, text: "World Day Against Child Labour. [[Education]] celebrates by assigning extra homework" },
  { month: 6, day: 28, text: "Paul Bunyan Day. His legendary axe could split [[Atoms]], or so lumberjacks claim" },
  { month: 7, day: 1, text: "International [[Chess]] Day. Pawns begin their annual protest for better working conditions" },
  { month: 7, day: 29, text: "International [[Painting|Tiger]] Day. Tigers demand to know why they're not in the [[Cats]] article" },
  { month: 8, day: 2, text: "[[Electricity]] Day. Benjamin Franklin's kite sends its regards from the storm" },
  { month: 8, day: 19, text: "World [[Photography]] Day. Everyone takes a photo of their [[Coffee]] to celebrate" },
  { month: 9, day: 10, text: "World Suicide Prevention Day. The [[Heart]] pledges to keep beating no matter how many horror movies you watch" },
  { month: 9, day: 22, text: "Autumn equinox: [[Photosynthesis]] workers begin filing for seasonal unemployment" },
  { month: 10, day: 10, text: "World Mental Health Day. The [[Brain]] admits it has been overthinking things since 1990" },
  { month: 10, day: 24, text: "United Nations Day. [[Democracy]] pats itself on the back while countries continue to argue" },
  { month: 11, day: 8, text: "World [[Earthquakes|Earthquake]] Awareness Day. Earth promises to give at least 5 seconds notice next time" },
  { month: 11, day: 19, text: "World Toilet Day. [[Water]] expresses mixed feelings about its role in the proceedings" },
  { month: 12, day: 1, text: "The first [[Trains|train]] sets off from Liverpool to Manchester. The train arrives 3 minutes late, starting a tradition" },
  { month: 12, day: 10, text: "Nobel Prize ceremony. Alfred Nobel is commemorated for inventing both dynamite and the guilt prize" },
  { month: 12, day: 15, text: "International [[Tea]] Day. The British Empire collectively nods in solemn approval" },
  { month: 1, day: 19, text: "National [[Cheese]] Lovers Day. France declares it a national holiday; Switzerland disagrees on principle" },
  { month: 2, day: 17, text: "Random Acts of Kindness Day. [[Cats]] remain unaffected" },
  { month: 3, day: 1, text: "World [[Bread|Compliment]] Day. [[Bread]] rises to the occasion" },
  { month: 6, day: 15, text: "Global [[Hurricanes|Wind]] Day. [[Clouds]] take the opportunity to relocate" },
  { month: 8, day: 30, text: "International [[Sushi]] Day. [[Rice]] is grateful for the recognition; fish less enthusiastic" },
  { month: 11, day: 30, text: "[[Computers|Computer]] Security Day. Your password is still 'password123' and everyone knows it" },
  { month: 12, day: 8, text: "[[Electricity]] is demonstrated publicly for the first time. [[Lightning]] files a copyright complaint" },
];
