// Curated topics by category for bulk article generation
// ~1000 topics across 20+ categories

export const topicsByCategory: Record<string, string[]> = {
  "Science": [
    "Mitosis", "Photons", "Thermodynamics", "Periodic Table", "Chemical Bonds",
    "Magnetism", "Sound Waves", "Light Spectrum", "Nuclear Fusion", "Relativity",
    "Quantum Mechanics", "String Theory", "Entropy", "Osmosis", "Bacteria",
    "Viruses", "Fungi", "Plate Tectonics", "Volcanoes", "Fossils",
    "Radioactivity", "Centrifugal Force", "Kinetic Energy", "Potential Energy",
    "Electromagnetic Spectrum", "Refraction", "Diffusion", "Catalysts",
    "Acid Rain", "Greenhouse Effect", "Ozone Layer", "Carbon Cycle",
    "Nitrogen Cycle", "Water Cycle", "Soil", "Minerals", "Crystals",
    "Static Electricity", "Friction", "Buoyancy", "Density",
    "Acceleration", "Momentum", "Velocity", "Mass", "Volume",
    "Hypothesis", "Scientific Method", "Microscope", "Telescope",
  ],
  "History": [
    "Roman Empire", "Medieval Period", "Renaissance", "Industrial Revolution",
    "French Revolution", "American Revolution", "World War I", "World War II",
    "Cold War", "Ancient Greece", "Viking Age", "Ottoman Empire",
    "Silk Road", "Crusades", "Black Death", "Spanish Inquisition",
    "Colonialism", "Slavery", "Civil Rights Movement", "Space Race",
    "Fall of the Berlin Wall", "Ancient China", "Mayan Civilization",
    "Aztec Empire", "Inca Empire", "Mongol Empire", "Byzantine Empire",
    "Samurai", "Knights", "Castles", "Pyramids of Giza",
    "Stonehenge", "Pompeii", "Cleopatra", "Julius Caesar",
    "Alexander the Great", "Genghis Khan", "Napoleon", "Queen Victoria",
    "Abraham Lincoln", "Martin Luther King Jr", "Mahatma Gandhi",
    "Nelson Mandela", "Winston Churchill", "Treaty of Versailles",
    "Declaration of Independence", "Magna Carta", "Printing Press",
    "Gunpowder", "Compass",
  ],
  "Food and drink": [
    "Sushi", "Pasta", "Tacos", "Curry", "Hamburger",
    "Ice Cream", "Bread", "Cheese", "Wine", "Beer",
    "Whiskey", "Vodka", "Champagne", "Espresso", "Matcha",
    "Kimchi", "Hummus", "Croissant", "Ramen", "Pho",
    "Dumplings", "Paella", "Fish and Chips", "Kebab", "Falafel",
    "Sourdough", "Butter", "Olive Oil", "Honey", "Maple Syrup",
    "Hot Dog", "Pretzel", "Donut", "Bagel", "Pancakes",
    "French Fries", "Popcorn", "Nachos", "Guacamole", "Salsa",
    "Tofu", "Tempeh", "Miso Soup", "Pad Thai", "Biryani",
    "Tiramisu", "Cheesecake", "Baklava", "Mochi", "Churros",
  ],
  "Technology": [
    "Artificial Intelligence", "Blockchain", "Virtual Reality",
    "Augmented Reality", "5G Networks", "Cloud Computing",
    "Machine Learning", "Internet of Things", "Cybersecurity",
    "Quantum Computing", "3D Printing", "Drones", "Self-Driving Cars",
    "Electric Vehicles", "Solar Panels", "Wind Turbines",
    "Nuclear Power", "Hydroelectric Power", "Battery Technology",
    "Semiconductors", "Microprocessors", "RAM", "Hard Drives",
    "Fiber Optics", "Wi-Fi", "Bluetooth", "GPS", "Satellites",
    "Rockets", "Space Station", "Mars Rovers", "Hubble Telescope",
    "CRISPR", "Nanotechnology", "Robotics", "Neural Networks",
    "Cryptocurrency", "NFTs", "Metaverse", "Algorithm",
    "Open Source Software", "Linux", "Programming Languages",
    "Databases", "APIs", "Web Browsers", "Search Engines",
    "Social Media", "Streaming Services", "Video Games",
  ],
  "Space": [
    "Mars", "Venus", "Jupiter", "Saturn", "Mercury",
    "Neptune", "Uranus", "Pluto", "Asteroid Belt", "Kuiper Belt",
    "Milky Way", "Andromeda Galaxy", "Nebula", "Supernova",
    "Neutron Stars", "White Dwarfs", "Red Giants", "Pulsars",
    "Quasars", "Dark Matter", "Dark Energy", "Big Bang",
    "Cosmic Microwave Background", "Solar Wind", "Aurora Borealis",
    "Comets", "Meteors", "Meteorites", "Moon Phases",
    "Solar Eclipse", "Lunar Eclipse", "Tides", "Constellations",
    "Zodiac", "Exoplanets", "Habitable Zone", "Space Debris",
    "International Space Station", "Apollo Missions", "Voyager Probes",
    "James Webb Space Telescope", "SpaceX", "NASA",
    "European Space Agency", "Astronaut Training",
    "Space Suits", "Zero Gravity", "Wormholes", "Time Dilation",
  ],
  "Mathematics": [
    "Pi", "Fibonacci Sequence", "Prime Numbers", "Infinity",
    "Calculus", "Algebra", "Geometry", "Trigonometry", "Statistics",
    "Probability", "Set Theory", "Number Theory", "Topology",
    "Fractals", "Golden Ratio", "Imaginary Numbers", "Matrices",
    "Logarithms", "Exponents", "Square Roots", "Pythagorean Theorem",
    "Euclid", "Euler", "Gauss", "Riemann Hypothesis",
    "Game Theory", "Chaos Theory", "Graph Theory", "Combinatorics",
    "Binary Numbers", "Hexadecimal", "Boolean Logic", "Venn Diagrams",
    "Normal Distribution", "Standard Deviation", "Mean Median Mode",
    "Polynomials", "Equations", "Inequalities", "Functions",
    "Derivatives", "Integrals", "Limits", "Vectors",
    "Complex Numbers", "Differential Equations", "Linear Algebra",
    "Discrete Mathematics", "Mathematical Proofs", "Axioms",
  ],
  "Nature": [
    "Rainforests", "Deserts", "Oceans", "Coral Reefs", "Mountains",
    "Rivers", "Lakes", "Glaciers", "Caves", "Islands",
    "Wolves", "Bears", "Eagles", "Sharks", "Whales",
    "Dolphins", "Elephants", "Lions", "Tigers", "Gorillas",
    "Penguins", "Flamingos", "Parrots", "Owls", "Hummingbirds",
    "Butterflies", "Bees", "Ants", "Spiders", "Octopuses",
    "Jellyfish", "Sea Turtles", "Chameleons", "Frogs", "Snakes",
    "Crocodiles", "Kangaroos", "Pandas", "Koalas", "Sloths",
    "Redwood Trees", "Bamboo", "Cacti", "Orchids", "Sunflowers",
    "Mushrooms", "Moss", "Ferns", "Seaweed", "Plankton",
  ],
  "Arts and culture": [
    "Mona Lisa", "Starry Night", "The Scream", "Guernica",
    "Impressionism", "Surrealism", "Cubism", "Pop Art",
    "Renaissance Art", "Baroque", "Abstract Art", "Street Art",
    "Photography", "Sculpture", "Pottery", "Origami",
    "Ballet", "Opera", "Jazz", "Rock and Roll",
    "Hip Hop", "Classical Music", "Electronic Music", "Blues",
    "Symphony Orchestra", "Piano", "Guitar", "Violin", "Drums",
    "Cinema", "Animation", "Theater", "Stand-Up Comedy",
    "Novel", "Poetry", "Short Story", "Graphic Novel",
    "Manga", "Anime", "Video Game Design", "Architecture",
    "Fashion", "Tattoos", "Graffiti", "Calligraphy",
    "Typography", "Graphic Design", "Interior Design",
    "Costume Design", "Set Design", "Sound Design",
  ],
  "Sports": [
    "Basketball", "Tennis", "Baseball", "Cricket", "Rugby",
    "Golf", "Boxing", "Wrestling", "Martial Arts", "Fencing",
    "Swimming", "Diving", "Surfing", "Skateboarding", "Snowboarding",
    "Skiing", "Ice Hockey", "Figure Skating", "Gymnastics", "Track and Field",
    "Marathon", "Triathlon", "Cycling", "Formula One", "NASCAR",
    "Horse Racing", "Polo", "Archery", "Shooting Sports", "Badminton",
    "Table Tennis", "Volleyball", "Handball", "Water Polo", "Rowing",
    "Sailing", "Rock Climbing", "Parkour", "Cheerleading", "Yoga",
    "Olympic Games", "World Cup", "Super Bowl", "Wimbledon",
    "Tour de France", "Olympics History", "Esports", "Chess Boxing",
    "Extreme Sports", "Paralympic Games",
  ],
  "Geography": [
    "Amazon River", "Sahara Desert", "Mount Everest", "Grand Canyon",
    "Great Barrier Reef", "Niagara Falls", "Dead Sea", "Mariana Trench",
    "Antarctica", "Arctic", "Bermuda Triangle", "Ring of Fire",
    "Continental Drift", "Tectonic Plates", "Time Zones", "International Date Line",
    "Equator", "Tropics", "Latitude and Longitude", "Map Projections",
    "Japan", "India", "Brazil", "Russia", "Canada",
    "China", "Egypt", "France", "Germany", "Italy",
    "Mexico", "South Africa", "Kenya", "Argentina", "Peru",
    "Thailand", "Vietnam", "Indonesia", "New Zealand", "Iceland",
    "Switzerland", "Norway", "Sweden", "Finland", "Denmark",
    "Netherlands", "Belgium", "Portugal", "Spain", "Greece",
  ],
  "Language": [
    "English Language", "Spanish Language", "Mandarin Chinese", "Arabic Language",
    "Hindi Language", "French Language", "German Language", "Japanese Language",
    "Korean Language", "Russian Language", "Portuguese Language", "Italian Language",
    "Sign Language", "Braille", "Morse Code", "Esperanto",
    "Latin", "Ancient Greek Language", "Sanskrit", "Hebrew Language",
    "Alphabet", "Grammar", "Syntax", "Semantics",
    "Phonetics", "Etymology", "Linguistics", "Dialects",
    "Slang", "Idioms", "Proverbs", "Metaphors",
    "Translation", "Interpreting", "Bilingualism", "Language Families",
    "Endangered Languages", "Pidgin Languages", "Creole Languages",
    "Hieroglyphics", "Cuneiform", "Runes", "Emoji",
    "Punctuation", "Vowels and Consonants", "Syllables",
    "Onomatopoeia", "Palindromes", "Anagrams", "Tongue Twisters",
  ],
  "Medicine": [
    "Immune System", "Vaccines", "Antibiotics", "Surgery",
    "Anesthesia", "Blood Types", "Heart", "Lungs",
    "Brain", "Liver", "Kidneys", "Skeleton",
    "Muscles", "Nervous System", "Digestive System", "Circulatory System",
    "Vitamins", "Minerals", "Nutrition", "Metabolism",
    "Allergies", "Asthma", "Diabetes", "Cancer",
    "Flu", "Common Cold", "Fever", "Headaches",
    "First Aid", "CPR", "X-Rays", "MRI",
    "Stethoscope", "Thermometer", "Blood Pressure", "Pulse",
    "Dentistry", "Optometry", "Pharmacy", "Nursing",
    "Mental Health", "Therapy", "Meditation", "Acupuncture",
    "Herbal Medicine", "Placebo Effect", "Clinical Trials",
    "Hippocratic Oath", "Red Cross",
  ],
  "Philosophy": [
    "Ethics", "Logic", "Metaphysics", "Epistemology",
    "Existentialism", "Stoicism", "Nihilism", "Utilitarianism",
    "Determinism", "Free Will", "Consciousness", "The Mind-Body Problem",
    "Plato", "Aristotle", "Socrates", "Descartes",
    "Kant", "Nietzsche", "Confucius", "Buddha",
    "The Trolley Problem", "Occam's Razor", "Pascal's Wager",
    "Allegory of the Cave", "Cogito Ergo Sum", "Social Contract",
    "Justice", "Beauty", "Truth", "Wisdom",
    "Happiness", "Virtue", "Morality", "Rights",
    "Democracy Philosophy", "Political Philosophy", "Philosophy of Science",
    "Philosophy of Language", "Philosophy of Mind", "Aesthetics",
    "Phenomenology", "Pragmatism", "Relativism", "Skepticism",
    "Empiricism", "Rationalism", "Idealism", "Materialism",
    "Dualism", "Monism",
  ],
  "Politics": [
    "Democracy", "Communism", "Capitalism", "Socialism",
    "Fascism", "Anarchism", "Liberalism", "Conservatism",
    "United Nations", "European Union", "NATO", "G7",
    "Constitution", "Parliament", "Congress", "Senate",
    "Elections", "Voting Systems", "Political Parties", "Lobbying",
    "Diplomacy", "Sanctions", "International Law", "Human Rights",
    "Freedom of Speech", "Freedom of Press", "Civil Liberties",
    "Taxation", "Welfare State", "Healthcare Policy", "Immigration Policy",
    "Foreign Policy", "Trade Agreements", "Climate Policy",
    "Nuclear Disarmament", "Peacekeeping", "Propaganda",
    "Censorship", "Whistleblowing", "Gerrymandering",
    "Political Polls", "Campaign Finance", "Filibuster",
    "Executive Orders", "Judicial Review", "Federalism",
    "Sovereignty", "Nationalism", "Globalization", "Populism",
  ],
  "Economics": [
    "Supply and Demand", "Inflation", "Recession", "GDP",
    "Stock Market", "Bonds", "Interest Rates", "Central Banks",
    "Federal Reserve", "Wall Street", "Cryptocurrency Markets",
    "Trade", "Tariffs", "Imports and Exports", "Balance of Trade",
    "Monopoly", "Competition", "Market Failure", "Externalities",
    "Unemployment", "Minimum Wage", "Labor Unions", "Gig Economy",
    "Real Estate Market", "Housing Bubble", "Mortgage",
    "Insurance", "Banking", "Credit Cards", "Debt",
    "Budget", "Fiscal Policy", "Monetary Policy", "Austerity",
    "Keynesian Economics", "Austrian Economics", "Marxist Economics",
    "Adam Smith", "Karl Marx", "John Maynard Keynes",
    "Milton Friedman", "Behavioral Economics", "Microeconomics",
    "Macroeconomics", "Economic Indicators", "Consumer Confidence",
    "Purchasing Power", "Cost of Living", "Income Inequality", "Poverty",
  ],
  "Psychology": [
    "Memory", "Perception", "Attention", "Learning",
    "Motivation", "Emotion", "Personality", "Intelligence",
    "Dreams", "Sleep Psychology", "Stress", "Anxiety",
    "Depression", "PTSD", "Phobias", "OCD",
    "Cognitive Biases", "Confirmation Bias", "Dunning-Kruger Effect",
    "Stockholm Syndrome", "Impostor Syndrome", "Placebo Effect Psychology",
    "Classical Conditioning", "Operant Conditioning", "Pavlov",
    "Sigmund Freud", "Carl Jung", "B.F. Skinner",
    "Abraham Maslow", "Maslow's Hierarchy of Needs",
    "Nature vs Nurture", "Child Development", "Adolescence",
    "Social Psychology", "Group Dynamics", "Conformity",
    "Obedience", "Milgram Experiment", "Stanford Prison Experiment",
    "Cognitive Dissonance", "Halo Effect", "Bystander Effect",
    "Optical Illusions", "Color Psychology", "Body Language",
    "Empathy", "Narcissism", "Introversion and Extroversion",
    "IQ Tests", "Emotional Intelligence",
  ],
  "Music": [
    "Piano Music", "Guitar Music", "Orchestra", "Choir",
    "Music Theory", "Sheet Music", "Musical Scales", "Chords",
    "Rhythm", "Melody", "Harmony", "Tempo",
    "The Beatles", "Elvis Presley", "Michael Jackson", "Madonna",
    "Mozart", "Beethoven", "Bach", "Chopin",
    "Bob Dylan", "David Bowie", "Prince", "Whitney Houston",
    "Reggae", "Country Music", "Folk Music", "Punk Rock",
    "Heavy Metal", "Grunge", "Disco", "Techno",
    "K-Pop", "J-Pop", "Bossa Nova", "Flamenco",
    "Gospel Music", "Soul Music", "R&B", "Funk",
    "Music Festivals", "Grammy Awards", "Billboard Charts",
    "Recording Studios", "Vinyl Records", "Cassette Tapes",
    "CDs", "MP3", "Music Streaming", "Karaoke",
  ],
  "Religion": [
    "Christianity", "Islam", "Hinduism", "Buddhism",
    "Judaism", "Sikhism", "Taoism", "Shinto",
    "Greek Mythology", "Norse Mythology", "Egyptian Mythology",
    "Roman Mythology", "Celtic Mythology", "Hindu Mythology",
    "The Bible", "The Quran", "The Torah", "The Vedas",
    "Prayer", "Meditation Practices", "Pilgrimage", "Fasting",
    "Heaven and Hell", "Reincarnation", "Karma", "Nirvana",
    "Churches", "Mosques", "Temples", "Synagogues",
    "Religious Holidays", "Christmas", "Easter", "Ramadan",
    "Diwali", "Hanukkah", "Eid", "Vesak",
    "Saints", "Prophets", "Angels", "Miracles",
    "Creation Myths", "Afterlife", "Sacred Texts", "Monasticism",
    "Religious Art", "Church Architecture", "Religious Music",
  ],
  "Transportation": [
    "Automobiles", "Trains", "Airplanes", "Ships",
    "Bicycles", "Motorcycles", "Buses", "Trams",
    "Submarines", "Helicopters", "Hot Air Balloons", "Zeppelins",
    "Canoes", "Sailboats", "Yachts", "Ferries",
    "Highways", "Bridges", "Tunnels", "Airports",
    "Ports", "Railway Stations", "Subway Systems", "Cable Cars",
    "Speed Limits", "Traffic Lights", "Road Signs", "Roundabouts",
    "Seat Belts", "Airbags", "Fuel Efficiency", "Electric Cars",
    "Maglev Trains", "Hyperloop", "Autonomous Vehicles", "Jet Engines",
    "Propellers", "Wheels", "Tires", "Suspension",
    "Cargo Ships", "Container Shipping", "Logistics",
    "Air Traffic Control", "Maritime Navigation", "Road Maps",
  ],
  "Fashion": [
    "Jeans", "T-Shirts", "Suits", "Dresses",
    "High Heels", "Sneakers", "Hats", "Sunglasses",
    "Jewelry", "Watches", "Handbags", "Scarves",
    "Silk", "Cotton", "Wool", "Leather",
    "Fashion Week", "Haute Couture", "Fast Fashion", "Sustainable Fashion",
    "Coco Chanel", "Versace", "Gucci", "Louis Vuitton",
    "Vintage Fashion", "Streetwear", "Athleisure", "Minimalism Fashion",
    "Makeup", "Perfume", "Hairstyles", "Nail Art",
    "Fashion Photography", "Modeling", "Fashion Magazines",
    "Color Trends", "Textile Manufacturing", "Sewing",
    "Knitting", "Embroidery", "Dyeing", "Pattern Making",
  ],
  "Architecture": [
    "Gothic Architecture", "Art Deco", "Modernism Architecture",
    "Brutalism", "Neoclassical Architecture", "Islamic Architecture",
    "Japanese Architecture", "Ancient Roman Architecture",
    "Skyscrapers", "Bridges Architecture", "Cathedrals", "Palaces",
    "Eiffel Tower", "Colosseum", "Taj Mahal", "Parthenon",
    "Empire State Building", "Burj Khalifa", "Sydney Opera House",
    "Sagrada Familia", "Great Wall of China", "Machu Picchu",
    "Frank Lloyd Wright", "Le Corbusier", "Zaha Hadid",
    "Sustainable Architecture", "Green Buildings", "Tiny Houses",
    "Interior Architecture", "Landscape Architecture",
    "Urban Planning", "City Design", "Public Spaces",
    "Building Materials", "Concrete", "Steel Construction", "Glass Facades",
    "Arches", "Domes", "Columns", "Flying Buttresses",
  ],
};

export function getAllTopics(): { topic: string; category: string }[] {
  const all: { topic: string; category: string }[] = [];
  for (const [category, topics] of Object.entries(topicsByCategory)) {
    for (const topic of topics) {
      all.push({ topic, category });
    }
  }
  return all;
}

export function getTopicsByCategory(category: string): string[] {
  return topicsByCategory[category] || [];
}

export function getAllCategories(): string[] {
  return Object.keys(topicsByCategory);
}
