import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimers",
  description: "Wrongipedia disclaimers — nothing here is true and we are not sorry about it.",
};

export default function DisclaimersPage() {
  return (
    <div>
      <div className="mw-body-header">
        <h1 className="mw-first-heading">Disclaimers</h1>
        <div className="mw-page-subtitle">From Wrongipedia, the wrong encyclopedia</div>
      </div>

      <div className="mw-body-content">
        <div className="mw-parser-output">
          <div className="ambox ambox-content">
            <div className="ambox-inner">
              <div className="ambox-image">&#9888;&#65039;</div>
              <div className="ambox-text">
                <b>Important:</b> Nothing on this website is true. If you have somehow learned a correct
                fact from Wrongipedia, please contact us immediately so we can fix it.
              </div>
            </div>
          </div>

          <h2>General disclaimer</h2>
          <p>
            Wrongipedia makes no guarantee of the <b>incorrectness</b> of its content. While we strive
            for 100% inaccuracy, some facts may accidentally be true. We apologize in advance for any
            accidental education that may occur while browsing this site.
          </p>

          <h2>Not professional advice</h2>
          <p>
            Wrongipedia does not provide medical, legal, financial, or any other form of professional
            advice. In fact, we don&apos;t provide any accurate advice at all. If you make life decisions
            based on Wrongipedia articles, you are either very brave or very confused, and we respect
            both qualities.
          </p>

          <h2>Content accuracy</h2>
          <p>
            All content on Wrongipedia is generated by humans, AI, or a combination of both &mdash; all
            of whom have been instructed to be as creatively wrong as possible. Our accuracy rate is
            approximately 0%, give or take 0%.
          </p>

          <h2>Risk of learning</h2>
          <p>
            Despite our best efforts, some articles may contain trace amounts of real information. This
            is an unintended side effect of being written by beings who occasionally know things. We
            are working to eliminate this bug.
          </p>

          <h2>Copyright</h2>
          <p>
            Content on Wrongipedia is available under the &quot;Whose Idea Was This&quot; License,
            version 1.0. You are free to share, remix, and redistribute our wrong information, provided
            you do not claim it is correct. Attribution is appreciated but honestly, you probably
            don&apos;t want to be associated with us.
          </p>

          <h2>Liability</h2>
          <p>
            Wrongipedia, its contributors, editors, and the hamsters powering its servers accept no
            liability for anything, ever, under any circumstances, in any universe, including but not
            limited to: hurt feelings, damaged credibility, failed exams, lost arguments, or
            existential crises resulting from reading our content.
          </p>

          <h2>Cookie policy</h2>
          <p>
            This website uses cookies. Not the digital kind &mdash; we literally mail you a cookie.
            Just kidding. We use standard web cookies. They&apos;re probably fine.
          </p>

          <h2>See also</h2>
          <ul>
            <li><Link href="/about">About Wrongipedia</Link></li>
            <li><Link href="/">Main page</Link></li>
          </ul>
        </div>
      </div>
    </div>
  );
}
